[build]
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
runner = "qemu-system-riscv64 -nographic -bios none -machine virt -kernel"
linker = "rust-lld"
rustflags = [
  "-C", "link-arg=linker.ld",
]
